package com.monopoly.monopoly_managment.domain.property.events;

public enum EventsEnum {
  CONTRACT_FINALIZED,
  CONTRACT_SIGNED,
  DEMOLISHED_IMPROVEMENT,
  MADE_IMPROVEMENT,
  MONOPOLY_ACQUIRED,
  MORTGAGE_CANCELLED,
  MORTGAGE_CONSTITUTED,
  OWNER_ASSIGNED,
  OWNER_REMOVED,
  OWNER_MODIFIED,
  PROPERTY_TYPE_CHANGED,
}
